### ISSUE TITLE
Error While installing package `The following exception probably indicates you have misconfigured DNS resolver(s)`

### ISSUE THREAD

**Issue by keyurkansara** [Aniket-IN/laravel-shiprocket#16]
I am getting this error while installing this package.

`The following exception probably indicates you have misconfigured DNS resolver(s)`

I am on windows 11 using php version 8.1

Please refer to this image for your reference.
![image](https://github.com/Aniket-IN/laravel-shiprocket/assets/16578606/748c93a4-b126-4b5a-98a6-2a96d1c5e5c6)

**Comment by Aniket-IN** [comment]
Hmm, weird. 
Looks like, you are not able to connect to Packagist repository.

The error shouldn't be specific to any composer package, 
you won't be able to install any other package with this issue.

Something to do with your internet maybe. 

Are you able to open this page in your browser? https://packagist.org/

**Comment by Aniket-IN** [comment]
Few things you could try:
- Flush your DNS cache with this command `ipconfig /flushdns`
- Changing your DNS to Google's or Cloudflare's DNS. ([Guide](https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10))

If still doesnt work, if you have a VPN try using that once.

Similar issues:
https://stackoverflow.com/questions/64690290/dns-resolver-issue-composer-2
